version: "3.4"
services:
  message-broker:
    build:
      context: .
      target: test
    container_name: "message-broker"
    depends_on:
      - "mq"
    environment:
      MQ_HOST: "mq:5672"
    image: "message-broker:test"
    links:
      - "mq"
  mq:
    container_name: "mq"
    image: "rabbitmq:3.9.12-management"
    ports:
      - "5672:5672"
