version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: docker/compose:1.22.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Test
          command: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
