name: CI
on:
  push:
    branches: ['**']
    tags-ignore: ['v*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: node:16.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install NPM dependencies
        run: npm install
      - name: Build
        run: npm run build
  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    container: docker/compose:1.22.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
      - name: Notify success
        if: ${{ success() }}
        uses: andrewscwei/slack-action@v1.0.0
        with:
          success: true
          webhook-url: ${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}
      - name: Notify failure
        if: ${{ failure() }}
        uses: andrewscwei/slack-action@v1.0.0
        with:
          success: false
          webhoook-url: ${{ secrets.SLACK_DEVOPS_WEBHOOK_URL }}

