name: CI
on:
  pull_request:
  push:
    branches-ignore: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      service:
        image: rabbitmq:3.12.7
        ports:
          - 5672:5672
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: andrewscwei/actions/node-build@v1
        with:
          postbuild-command: npm test
  notify:
    name: Notify
    needs: [build]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/telegram-action@v1
        with:
          success: ${{ needs.build.result == 'success' }}
          cancelled: ${{ needs.build.result == 'cancelled' }}
          bot-token: ${{ secrets.TELEGRAM_DEVOPS_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_DEVOPS_CHAT_ID }}
